# Stage 1: Infrastructure
# All AWS resources: Secrets, ACM, VPC, EKS, RDS, IAM
#
# Prerequisites: Run scripts/create-tfstate-backend.sh first
# Used by: 02-apps

# Note: terraform block is in versions.tf
# Note: AWS provider is generated by Terragrunt

# Kubernetes/Helm providers - configured after EKS exists
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_ca_certificate)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.name, "--region", var.region]
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_ca_certificate)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", local.name, "--region", var.region]
    }
  }
}

# =============================================================================
# Secrets Manager
# =============================================================================

# Generate random password for RDS
resource "random_password" "db_password" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "${local.name}/db-credentials"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = "coder"
    password = random_password.db_password.result
  })
}

resource "aws_secretsmanager_secret" "github_oauth" {
  name                    = "${local.name}/github-oauth"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "github_oauth" {
  secret_id = aws_secretsmanager_secret.github_oauth.id
  secret_string = jsonencode({
    client_id     = var.github_oauth_client_id
    client_secret = var.github_oauth_client_secret
  })
}

# Grafana GitHub OAuth (optional)
resource "aws_secretsmanager_secret" "grafana_github_oauth" {
  count                   = var.grafana_github_oauth_client_id != "" ? 1 : 0
  name                    = "${local.name}/grafana-github-oauth"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "grafana_github_oauth" {
  count     = var.grafana_github_oauth_client_id != "" ? 1 : 0
  secret_id = aws_secretsmanager_secret.grafana_github_oauth[0].id
  secret_string = jsonencode({
    client_id     = var.grafana_github_oauth_client_id
    client_secret = var.grafana_github_oauth_client_secret
  })
}

# =============================================================================
# ACM Certificate + DNS Validation
# =============================================================================

data "aws_route53_zone" "main" {
  name         = var.route53_zone_name
  private_zone = false
}

resource "aws_acm_certificate" "coder" {
  domain_name               = var.domain
  subject_alternative_names = [var.wildcard_domain]
  validation_method         = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  tags = {
    Name = "${local.name}-cert"
  }
}

resource "aws_route53_record" "cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.coder.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 300
  type            = each.value.type
  zone_id         = data.aws_route53_zone.main.zone_id
}

resource "aws_acm_certificate_validation" "coder" {
  certificate_arn         = aws_acm_certificate.coder.arn
  validation_record_fqdns = [for record in aws_route53_record.cert_validation : record.fqdn]

  timeouts {
    create = "30m"
  }
}

# =============================================================================
# VPC
# =============================================================================
module "vpc" {
  source = "../modules/vpc"

  name   = local.name
  region = var.region
}

# =============================================================================
# EKS
# =============================================================================
module "eks" {
  source = "../modules/eks"

  name               = local.name
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnet_ids
  public_subnet_ids  = module.vpc.public_subnet_ids
  auto_mode          = var.auto_mode
}

# =============================================================================
# RDS
# =============================================================================
module "rds" {
  source = "../modules/rds"

  name                      = local.name
  vpc_id                    = module.vpc.vpc_id
  private_subnet_ids        = module.vpc.private_subnet_ids
  vpc_cidr                  = module.vpc.vpc_cidr
  db_credentials_secret_arn = aws_secretsmanager_secret.db_credentials.arn

  depends_on = [aws_secretsmanager_secret_version.db_credentials]
}

# =============================================================================
# IAM (IRSA roles)
# =============================================================================
module "iam" {
  source = "../modules/iam"

  name              = local.name
  oidc_provider_arn = module.eks.oidc_provider_arn
  oidc_provider_url = module.eks.oidc_provider_url
  auto_mode         = var.auto_mode
}


