# Stage 2: Applications
# Deploys Coder and Observability stack to EKS cluster
#
# Depends on: 01-infra
# Used by: 03-day2

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }
  }
}

# =============================================================================
# Variables (passed from Terragrunt)
# =============================================================================

variable "region" {
  type    = string
  default = "us-west-2"
}

variable "env_name" {
  type        = string
  description = "Environment name prefix"
  default     = "demo"
}

variable "cluster_name" {
  type        = string
  description = "EKS cluster name"
}

variable "cluster_endpoint" {
  type        = string
  description = "EKS cluster endpoint"
}

variable "cluster_ca_certificate" {
  type        = string
  description = "EKS cluster CA certificate (base64)"
}

variable "vpc_id" {
  type        = string
  description = "VPC ID"
}

variable "public_subnet_ids" {
  type        = list(string)
  description = "Public subnet IDs"
}

variable "db_connection_url" {
  type        = string
  sensitive   = true
  description = "RDS connection URL"
}

variable "db_host" {
  type        = string
  description = "RDS endpoint hostname"
}

variable "db_password" {
  type        = string
  sensitive   = true
  description = "RDS password"
}

variable "coder_role_arn" {
  type        = string
  description = "IAM role ARN for Coder service account"
}

variable "external_secrets_role_arn" {
  type        = string
  description = "IAM role ARN for External Secrets Operator"
}

variable "route53_zone_id" {
  type        = string
  description = "Route53 hosted zone ID"
}

variable "acm_certificate_arn" {
  type        = string
  description = "ACM certificate ARN"
}

variable "domain" {
  type        = string
  description = "Coder access URL domain"
}

variable "wildcard_domain" {
  type        = string
  description = "Wildcard domain for workspace apps"
}

variable "grafana_domain" {
  type        = string
  description = "Grafana external access domain (empty = no external access)"
  default     = ""
}

variable "github_oauth_secret_arn" {
  type        = string
  description = "Secrets Manager ARN for GitHub OAuth credentials"
}

variable "github_allowed_orgs" {
  type        = string
  description = "GitHub organization(s) allowed for OAuth login"
}

# =============================================================================
# Grafana GitHub OAuth (optional)
# =============================================================================
variable "grafana_github_oauth_client_id" {
  type        = string
  description = "GitHub OAuth App client ID for Grafana"
  default     = ""
}

variable "grafana_github_oauth_client_secret" {
  type        = string
  sensitive   = true
  description = "GitHub OAuth App client secret for Grafana"
  default     = ""
}

variable "grafana_github_allowed_orgs" {
  type        = string
  description = "Comma-separated list of GitHub organizations allowed to access Grafana"
  default     = ""
}

variable "coder_version" {
  type        = string
  description = "Coder Helm chart version (set via TF_VAR_coder_version or root terragrunt.hcl)"
  default     = "2.30.0"
}

# =============================================================================
# Providers
# =============================================================================
# Note: AWS provider is generated by terragrunt (see root terragrunt.hcl)

provider "kubernetes" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_ca_certificate)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name, "--region", var.region]
  }
}

provider "helm" {
  kubernetes {
    host                   = var.cluster_endpoint
    cluster_ca_certificate = base64decode(var.cluster_ca_certificate)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", var.cluster_name, "--region", var.region]
    }
  }
}

# =============================================================================
# Coder
# =============================================================================
module "coder" {
  source = "../modules/coder"

  name                   = var.cluster_name
  cluster_name           = var.cluster_name
  cluster_endpoint       = var.cluster_endpoint
  cluster_ca_certificate = var.cluster_ca_certificate

  domain          = var.domain
  wildcard_domain = var.wildcard_domain

  acm_certificate_arn = var.acm_certificate_arn

  vpc_id            = var.vpc_id
  public_subnet_ids = var.public_subnet_ids

  coder_role_arn            = var.coder_role_arn
  external_secrets_role_arn = var.external_secrets_role_arn

  db_connection_url       = var.db_connection_url
  github_oauth_secret_arn = var.github_oauth_secret_arn
  github_allowed_orgs     = var.github_allowed_orgs

  route53_zone_id = var.route53_zone_id
  coder_version   = var.coder_version
}

# =============================================================================
# Observability (Grafana, Prometheus, Loki)
# =============================================================================
module "observability" {
  source = "../modules/observability"

  name            = var.cluster_name
  coder_namespace = module.coder.namespace

  db_host     = var.db_host
  db_password = var.db_password

  grafana_domain      = var.grafana_domain
  acm_certificate_arn = var.acm_certificate_arn
  route53_zone_id     = var.route53_zone_id

  # Grafana GitHub OAuth (optional)
  grafana_github_oauth_enabled = var.grafana_github_oauth_client_id != ""
  grafana_github_allowed_orgs  = var.grafana_github_allowed_orgs
  grafana_root_url             = var.grafana_domain != "" ? "https://${var.grafana_domain}" : ""

  depends_on = [module.coder]
}
