# Stage 3: Day 2 Operations
# Post-deployment configuration requiring manual CODER_TOKEN
#
# Resources:
#   - Coder License (optional, enterprise)
#   - Provisioner Key
#   - External Provisioner Helm release
#
# Depends on: 02-apps (Coder must be running)
# Requires: CODER_TOKEN environment variable
#
# This stage is auto-skipped by Terragrunt if CODER_TOKEN is not set

terraform {
  required_providers {
    coderd = {
      source  = "coder/coderd"
      version = "~> 0.0.12"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }
  }
}

variable "coder_url" {
  description = "Coder access URL (e.g., https://dev.example.com)"
  type        = string
}

variable "coder_token" {
  description = "Coder API token (create with: coder tokens create --lifetime 8760h)"
  type        = string
  sensitive   = true
  default     = "" # Set via CODER_TOKEN env var
}

variable "coder_namespace" {
  description = "Kubernetes namespace where Coder is deployed"
  type        = string
  default     = "coder"
}

variable "license_key" {
  description = "Coder Enterprise license key (optional)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "coder_version" {
  type        = string
  description = "Coder Helm chart version (set via TF_VAR_coder_version or root terragrunt.hcl)"
  default     = "2.30.0"
}

variable "cluster_name" {
  description = "EKS cluster name"
  type        = string
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "env_name" {
  description = "Environment name prefix for resources"
  type        = string
  default     = ""
}

variable "provisioner_replicas" {
  description = "Number of provisioner replicas"
  type        = number
  default     = 5
}

variable "provisioner_role_arn" {
  description = "IAM role ARN for provisioner service account (IRSA)"
  type        = string
}

# =============================================================================
# Providers
# =============================================================================
# Note: AWS provider is generated by terragrunt (see root terragrunt.hcl)

provider "coderd" {
  url   = var.coder_url
  token = var.coder_token
}

# Get EKS cluster info for Helm provider
data "aws_eks_cluster" "coder" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "coder" {
  name = var.cluster_name
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.coder.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.coder.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.coder.token
  }
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.coder.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.coder.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.coder.token
}

# =============================================================================
# License (Enterprise only)
# =============================================================================

resource "coderd_license" "main" {
  count   = var.license_key != "" ? 1 : 0
  license = var.license_key

  lifecycle {
    create_before_destroy = true
  }
}

# =============================================================================
# Provisioner Key
# =============================================================================

data "coderd_organization" "default" {
  is_default = true
}

resource "coderd_provisioner_key" "main" {
  name            = "terraform-managed"
  organization_id = data.coderd_organization.default.id

  depends_on = [coderd_license.main]
}

# =============================================================================
# Provisioners Helm Release
# =============================================================================

# Create Kubernetes secret for provisioner key
resource "kubernetes_secret" "provisioner_key" {
  metadata {
    name      = "coder-provisioner-key"
    namespace = "coder"
  }

  data = {
    key = coderd_provisioner_key.main.key
  }
}

resource "helm_release" "coder_provisioner" {
  name       = "coder-provisioner"
  repository = "https://helm.coder.com/v2"
  chart      = "coder-provisioner"
  namespace  = "coder"
  version    = var.coder_version

  values = [yamlencode({
    coder = {
      replicaCount = var.provisioner_replicas

      serviceAccount = {
        create = true
        name   = "coder-provisioner"
        annotations = {
          "eks.amazonaws.com/role-arn" = var.provisioner_role_arn
        }
      }

      env = [
        {
          name  = "CODER_URL"
          value = var.coder_url
        },
      ]

      resources = {
        requests = {
          cpu    = "1000m"
          memory = "1Gi"
        }
        limits = {
          cpu    = "1000m"
          memory = "1Gi"
        }
      }
    }

    provisionerDaemon = {
      pskSecretName = "" # Disable deprecated PSK
      keySecretName = "coder-provisioner-key"
      keySecretKey  = "key"
    }
  })]

  depends_on = [kubernetes_secret.provisioner_key]
}

# =============================================================================
# RBAC: Bind provisioner SA to coder-provisioner ClusterRole in coder-workspaces
# =============================================================================
resource "kubernetes_role_binding" "provisioner_workspaces" {
  metadata {
    name      = "coder-provisioner-workspaces"
    namespace = "coder-workspaces"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "coder-provisioner" # Created in main deployment
  }

  subject {
    kind      = "ServiceAccount"
    name      = "coder-provisioner"
    namespace = "coder"
  }
}

# =============================================================================
# Outputs
# =============================================================================

output "provisioner_key_name" {
  description = "Name of the provisioner key"
  value       = coderd_provisioner_key.main.name
}

output "license_applied" {
  description = "Whether a license was applied"
  value       = var.license_key != ""
  sensitive   = true
}
